# Generated by Django 5.1.4 on 2025-01-13 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCreateform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=50)),
                ('for_class', models.CharField(choices=[('preprimary', 'PrePrimary'), ('primary', 'Primary'), ('highschool', 'High School')], max_length=20)),
                ('duration', models.CharField(max_length=15)),
                ('teacher_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('prerequites', models.CharField(max_length=100)),
                ('course_outcomes', models.CharField(max_length=100)),
                ('thubmnail', models.FileField(blank=True, null=True, upload_to='uploads/thumbnail/')),
                ('classnote', models.FileField(blank=True, null=True, upload_to='uploads/classnote/')),
                ('coursecontent', models.ImageField(blank=True, null=True, upload_to='uploads/coursecontent/')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_courses', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
