# Generated by Django 5.1.4 on 2025-01-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_coursecreateform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecreateform',
            name='coursecontent',
            field=models.FileField(blank=True, null=True, upload_to='uploads/coursecontent/'),
        ),
        migrations.AlterField(
            model_name='coursecreateform',
            name='thubmnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/thumbnail/'),
        ),
    ]
