# Generated by Django 5.1.4 on 2025-01-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_coursecreateform_coursecontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecreateform',
            name='current_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
