# Generated by Django 5.1.4 on 2025-01-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_coursecreateform_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecreateform',
            name='thubmnail',
            field=models.FileField(blank=True, null=True, upload_to='uploads/thumbnail/'),
        ),
    ]
