# Generated by Django 5.1.4 on 2025-01-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_coursecreateform_thubmnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecreateform',
            name='thubmnail',
        ),
        migrations.AddField(
            model_name='coursecreateform',
            name='coursethubmnail',
            field=models.FileField(blank=True, null=True, upload_to='uploads/coursethumbnail/'),
        ),
    ]
