# Generated by Django 5.1.4 on 2025-01-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_coursecreateform_thubmnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecreateform',
            name='coursethubmnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/coursethumbnail/'),
        ),
    ]
