# Generated by Django 5.1.4 on 2025-02-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_coursecreateform_coursethubmnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecreateform',
            name='coursethubmnail',
            field=models.FileField(blank=True, null=True, upload_to='uploads/coursethumbnail/'),
        ),
    ]
