# Generated by Django 5.1.4 on 2025-02-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_coursecreateform_coursethubmnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecreateform',
            name='courseassessment',
            field=models.FileField(blank=True, null=True, upload_to='upload/courseassessment/'),
        ),
    ]
