# Generated by Django 5.1.4 on 2025-02-19 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_coursecreateform_courseassessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCreateform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('topic', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
                ('for_class', models.CharField(max_length=10)),
                ('joinLink', models.URLField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
