# Generated by Django 5.1.4 on 2025-03-03 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_classcreateform_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lwfassessmentcreateform',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
