# Generated by Django 5.1.4 on 2025-03-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_lwfassessmentcreateform_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lwfassessmentcreateform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
