# Generated by Django 5.1.4 on 2025-03-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_question_option_quiz_question_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
