# Generated by Django 5.1.4 on 2025-03-15 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_remove_question_quiz_remove_quiz_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadlineManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('for_class', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=250)),
                ('deadline', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('content', models.FileField(upload_to='uploads/LWFAssignment/')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_assignment', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
