# Generated by Django 5.1.4 on 2025-03-15 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_deadlinemanagement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadlinemanagement',
            name='status',
        ),
    ]
