# Generated by Django 5.1.4 on 2025-03-23 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_instructorfeedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructorfeedback',
            old_name='submitted_by',
            new_name='uploaded_by',
        ),
    ]
