# Generated by Django 5.1.4 on 2025-03-23 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_rename_submitted_by_instructorfeedback_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorfeedback',
            name='uploaded_by',
        ),
    ]
