# Generated by Django 5.1.4 on 2025-03-23 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_remove_instructorfeedback_uploaded_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstructorFeedback',
            new_name='InstructorFeedbackForm',
        ),
    ]
