version: '3.8'

services:
  web:
    build: .
    command: gunicorn backendpart.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      # Database Configuration (use your AWS RDS hostname)
      - POSTGRES_DB=lms
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Arghya2002
      - POSTGRES_HOST=lms.c52244sqy91z.ap-south-1.rds.amazonaws.com
      - POSTGRES_PORT=5432

      # Email Configuration
      - EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=True
      - EMAIL_HOST_USER=eduhublmsofficials@gmail.com
      - EMAIL_HOST_PASSWORD=otgw rzoi jsao pcmw

      # AWS S3 Configuration (Optional)
      - AWS_ACCESS_KEY_ID=AKIA5MSUBVORPWUDFLPJ
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_STORAGE_BUCKET_NAME=lmseduhub
      - AWS_S3_REGION_NAME=ap-south-1

    volumes:
      - ./app:/app  # optional for development

volumes:
  postgres_data:
