version: '3.8'

services:
  web:
    build: .
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      # Database Configuration
      - POSTGRES_DB=Eduhub
      - POSTGRES_USER=arghya
      - POSTGRES_PASSWORD=arghya1234
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

      # Email Configuration
      - EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=True
      - EMAIL_HOST_USER=eduhublmsofficials@gmail.com
      - EMAIL_HOST_PASSWORD=otgw rzoi jsao pcmw

      # AWS Configuration (Optional, if using boto3)
      - AWS_ACCESS_KEY_ID=AKIA5MSUBVORPWUDFLPJ
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_STORAGE_BUCKET_NAME=lmseduhub
      - AWS_S3_REGION_NAME=ap-south-1

    depends_on:
      - db
    volumes:
      - ./app:/app  # Maps your local code to the container for development (optional)

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: Eduhub
      POSTGRES_USER: arghya
      POSTGRES_PASSWORD: arghya1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
